Display messages for configure,update and delete command.
vmware-tanzu/vsphere-kubernetes-drivers-operator pull request #109
Opened 2021-12-06 05:53 UTC by ridaz

**What type of PR is this?**
> /kind enhancement

**What this PR does / why we need it**:

Displays an appropriate message to the user after the command is invoked.
This PR will bring in the following changes :
1. vdoctl configure compatibility-matrix - Tip for the user since matrix has been configured, they can proceed with deploy VDO.
2. vdoctl delete - Message displaying since vdoctl delete has been invoked, the deployments will be deleted.
3. vdoctl update-matrix - Message displaying matrix has been updated successfully.

**Which issue(s) this PR fixes**:

Fixes #108 

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
/kind TESTED

**Test Report**:

```
bin/vdoctl configure cm
✔ Web URL
Web URL https://raw.githubusercontent.com/ridaz/Sample-files/main/sample.yaml
Tip: Compatibility matrix has been configured, you might want to try 'vdoctl deploy' to deploy VDO
```

```
bin/vdoctl delete
Since you have invoked delete VDO command, eventually the deployments will be deleted.
```

```
bin/vdoctl update compatibility-matrix https://raw.githubusercontent.com/ridaz/Sample-files/main/matrix.yaml
Compatibility matrix has been updated successfully.
```

**Special notes for your reviewer**:

2021-12-06 09:04 UTC, asifdxtreme commented on vdoctl/cmd/configure_matrix.go
> +		fmt.Println("Tip: Compatibility matrix has been configured, you might want to try 'vdoctl deploy' to deploy VDO.")
`Tip: Compatibility matrix has been configured, you might want to try 'vdoctl configure drivers' to configure Drivers.`

Flow is something like this
Deploy->Configure Matrix -> Configure Driver -> Check Status

2021-12-07 04:25 UTC, asifdxtreme approved these changes
LGTM

2021-12-07 04:55 UTC, aggarwalta approved these changes
LGTM, thanks!

2021-12-07 12:44 UTC, jvrahav requested changes

2021-12-07 12:44 UTC, jvrahav commented on vdoctl/cmd/delete.go
> +		fmt.Println("Since you have invoked delete VDO command, eventually the deployments will be deleted.")
lets word this as 
This command deletes the VDO operator deployment eventually the operator pods will be deleted

2021-12-07 12:44 UTC, jvrahav commented on vdoctl/cmd/delete.go
> +		fmt.Println("Since you have invoked delete VDO command, eventually the deployments will be deleted.")
is it possible to modify the delete command to vdoctl delete vdo

2021-12-07 14:29 UTC, jvrahav approved these changes

2021-12-07 19:30 UTC, merged