Support to fetch vSphere and k8s Version from k8s cluster and fetch corresponding Deployment Yamls
vmware-tanzu/vsphere-kubernetes-drivers-operator pull request #12
Opened 2021-09-02 07:45 UTC by ridaz

**This PR brings in the following support :**
1. Fetch vSphere and k8s version dynamically
2. Fetch CPI and CSI deployment yamls for corresponding vSphere and k8s version from the compatibility matrix
3. Unit tests for different cases of versions/yamls.

Ran the unit tests : 

```
?       github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator     [no test files]
?       github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/api/v1alpha1        [no test files]
ok      github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/controllers 11.409s coverage: 26.8% of statements
ok      github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/pkg/client  11.063s coverage: 60.0% of statements
?       github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/pkg/context [no test files]
ok      github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/pkg/drivers/cpi     0.388s  coverage: 88.0% of statements
ok      github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/pkg/drivers/csi     0.748s  coverage: 77.1% of statements
?       github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/pkg/models  [no test files]
ok      github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/pkg/session 0.746s  coverage: 61.2% of statements
```

```
kubectl get pods -A

NAMESPACE           NAME                                     READY   STATUS    RESTARTS   AGE
kube-system         vsphere-cloud-controller-manager-dfl97   1/1     Running   0          3m16s
kube-system         vsphere-csi-controller-55f949b89-fvvjv   6/6     Running   0          2m59s
kube-system         vsphere-csi-node-f79nl                   3/3     Running   0          2m58s
kube-system         vsphere-csi-node-vn57x                   3/3     Running   0          2m59s
vmware-system-vdo   vdo-controller-manager-d57b9684d-ggt6t   2/2     Running   0          3m42s

```
```

kubectl describe nodes | grep ProviderID
ProviderID:                   vsphere://423fa6d2-76c2-c6c0-cd3a-5e98ead5d42a
ProviderID:                   vsphere://423fd8bc-d5d4-c071-3055-52cae661ef83
```

```
kubectl get vdoconfig -A -o yaml
apiVersion: v1
items:
- apiVersion: vdo.vmware.com/v1alpha1
  kind: VDOConfig
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"vdo.vmware.com/v1alpha1","kind":"VDOConfig","metadata":{"annotations":{},"name":"vdoconfig-sample","namespace":"vmware-system-vdo"},"spec":{"cloudProvider":{"vsphereCloudConfigs":["vspherecloudconfig-sample"]},"storageProvider":{"vsphereCloudConfig":"vspherecloudconfig-sample"}}}
    creationTimestamp: "2021-09-01T21:19:55Z"
    generation: 1
    name: vdoconfig-sample
    namespace: vmware-system-vdo
    resourceVersion: "87264"
    uid: 4691f655-e76d-4518-8309-968f86c3d8eb
  spec:
    cloudProvider:
      vsphereCloudConfigs:
      - vspherecloudconfig-sample
    storageProvider:
      vsphereCloudConfig: vspherecloudconfig-sample
  status:
    cpi:
      'nodeStatus ':
        master01: ready
        worker01: ready
      phase: Configured
    csi:
      phase: Configuring
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

```

```
kubectl describe pvc example-vanilla-block-pvc
Name:          example-vanilla-block-pvc
Namespace:     default
StorageClass:  k8s-default-storage
Status:        Bound
Volume:        pvc-f8f9fce8-ef58-4393-bfe0-56a03e662178
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: csi.vsphere.vmware.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      2Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type    Reason                 Age   From                                                                                                Message
  ----    ------                 ----  ----                                                                                                -------
  Normal  ExternalProvisioning   66s   persistentvolume-controller                                                                         waiting for a volume to be created, either by external provisioner "csi.vsphere.vmware.com" or manually created by system administrator
  Normal  Provisioning           66s   csi.vsphere.vmware.com_vsphere-csi-controller-55f949b89-fvvjv_cf28ca96-ca83-4f96-ba5d-e6462c0e6a42  External provisioner is provisioning volume for claim "default/example-vanilla-block-pvc"
  Normal  ProvisioningSucceeded  62s   csi.vsphere.vmware.com_vsphere-csi-controller-55f949b89-fvvjv_cf28ca96-ca83-4f96-ba5d-e6462c0e6a42  Successfully provisioned volume pvc-f8f9fce8-ef58-4393-bfe0-56a03e662178

```

2021-09-02 19:27 UTC, jvrahav requested changes
can we move this to a function say fetch CheckCompatAndRetrieveSpec

2021-09-02 19:51 UTC, jvrahav requested changes

2021-09-02 19:51 UTC, jvrahav commented on controllers/vdoconfig_controller.go
> +	k8sServerVersion, err := discoveryClient.ServerVersion()
Can we move this to a function say FetchCompatibleVersions

2021-09-02 19:51 UTC, jvrahav commented on controllers/vdoconfig_controller.go
>  		vdoctx.Logger.V(4).Info("CSI deployment yamls : ", "list", csiDeploymentYamls)
we can avoid logging the url of spec files

2021-09-02 19:51 UTC, jvrahav commented on controllers/vdoconfig_controller.go
> +		vsphereCloudConfigsList = append(vsphereCloudConfigsList, vdoConfig.Spec.StorageProvider.VsphereCloudConfig)
If CPI is not configured would this cause a NIL reference exception ???

2021-09-02 19:51 UTC, jvrahav commented on controllers/vdoconfig_controller.go
> +	minVersionList := strings.Split(minVersion, ".")
seems https://github.com/hashicorp/go-version would be a better fit here to compare versions

2021-09-02 19:51 UTC, jvrahav commented on controllers/vdoconfig_controller.go
> +		if (strings.Contains(supportedVersionList[x], "x")) || (strings.Contains(supportedVersionList[x], "X")) {
please explore using https://github.com/hashicorp/go-version for version comparisons

2021-09-03 16:39 UTC, aggarwalta commented on controllers/vdoconfig_controller.go
> +}
This code seems redundant with the already existing function reconcileVCCredentials. Can we try to refactor this?

2021-09-03 17:09 UTC, jvrahav requested changes

2021-09-03 17:09 UTC, jvrahav commented on controllers/vdoconfig_controller.go
> +
we should just return session here. the rest of the code in the function isnt required

2021-09-03 17:09 UTC, jvrahav commented on controllers/vdoconfig_controller.go
> +		if err != nil {
check for error before appending to list

2021-09-03 17:09 UTC, jvrahav commented on controllers/vdoconfig_controller.go
> +func (r *VDOConfigReconciler) CheckCompatAndRetrieveSpec(matrixConfigUrl string, ctx vdocontext.VDOContext, req ctrl.Request, vdoConfig *vdov1alpha1.VDOConfig) error {
use context as first parameter

2021-09-03 17:09 UTC, jvrahav commented on controllers/vdoconfig_controller.go
> +	if cpiVersion == "" || len(cpiVersion) <= 0 {
check for length is sufficient

2021-09-03 17:09 UTC, jvrahav commented on controllers/vdoconfig_controller.go
> +	if csiVersion == "" || len(csiVersion) <= 0 {
check for length is sufficient

2021-09-03 18:37 UTC, aggarwalta commented on controllers/vdoconfig_controller.go
> +	}
We can use the existing function **fetchVcCredentials** for this.

2021-09-04 05:43 UTC, jvrahav approved these changes
Thanks for making the changes and adding the tests

2021-09-05 10:51 UTC, aggarwalta approved these changes
LGTM, thanks!

2021-09-06 05:11 UTC, asifdxtreme approved these changes
LGTM

2021-09-06 06:07 UTC, merged