Getting started from release Guide
vmware-tanzu/vsphere-kubernetes-drivers-operator pull request #124
Opened 2021-12-10 13:41 UTC by ridaz

**What type of PR is this?**
 /kind documentation

**What this PR does / why we need it**:
This PR will add a Getting started for release guide containing details about the assets delivered in each release and steps to be performed in order to deploy VDO along with CloudProvider and StorageProvider.

**Which issue(s) this PR fixes**:

Fixes #

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> /kind NOT-TESTED

**Test Report**:

**Special notes for your reviewer**:

2021-12-13 10:41 UTC, jvrahav commented on docs/getting-started-from-release.md
> +Once the VDO is deployed, you will see that the VDO manager pod is in `CreateConfigError` state and expects the compatibility matrix to be present
This needs to change based on the latest code. we need to talk about the default compatibility matrix here.
we need to talk about where the default file is available and how they can configure the compatibility if required

2021-12-13 10:47 UTC, jvrahav commented on docs/getting-started-from-release.md
> +Once the VDO is deployed, you will see that the VDO manager pod is in `CreateConfigError` state and expects the compatibility matrix to be present
for each command lets ensure that we have line pointing to the command documentation

2021-12-13 10:49 UTC, jvrahav requested changes

2021-12-13 10:49 UTC, jvrahav commented on docs/getting-started-from-release.md
> +
it will be great if we can build it a user flow in the doc to illustrate the steps

2021-12-14 15:02 UTC, jvrahav commented on docs/getting-started-from-release.md
> +Once the VDO is deployed, you will see that the VDO manager pod is in `CreateConfigError` state and expects the compatibility matrix to be present
as discussed, since we are deploying VDO with required pre-requisites we will not run into CreateConfigError

2021-12-14 20:43 UTC, asifdxtreme commented
@ridaz , Please pull in the latest changes and add this file `docs/getting-started` guide, also add the link to the same in https://github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/blob/main/docs/getting-started.md#choose-your-deployment-schemes

2021-12-23 06:25 UTC, aggarwalta approved these changes
LGTM, thanks!

2021-12-23 15:52 UTC, jvrahav approved these changes

2021-12-23 15:56 UTC, merged