Normalize the current Kubernetes versions for Openshift
vmware-tanzu/vsphere-kubernetes-drivers-operator pull request #130
Opened 2021-12-13 18:01 UTC by asifdxtreme

2021-12-13 18:02 UTC, lgayatri approved these changes

2021-12-14 03:43 UTC, aggarwalta approved these changes
LGTM, thanks!

2021-12-14 14:29 UTC, jvrahav requested changes
can we add a unit test to verify this

2021-12-14 21:16 UTC, asifdxtreme commented
@jvrahav I have added the UT to test the `+` scenario, please review

2021-12-14 21:21 UTC, jvrahav approved these changes

2021-12-14 21:21 UTC, merged