Update "use-csinode-id" key in the internal-feature-states.csi.vsphere.vmware.com config map
vmware-tanzu/vsphere-kubernetes-drivers-operator pull request #135
Opened 2021-12-21 15:15 UTC by ridaz

**What type of PR is this?**
 /kind enhancement

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #131 

**Test Report Added?**:
> /kind TESTED

**Test Report**:

This PR brings in the following change :
 Update "use-csinode-id" key in `internal-feature-states.csi.vsphere.vmware.com` config map for CSI version 2.5.0 and above.
In order to use the csi driver so that it does not rely on the Vsphere cloud provider to obtain the VM node uuid

**1. Test Results for Live k8s cluster** 

_Tested with CSI version 2.3.0_

```
bin/vdoctl deploy --spec https://github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/releases/download/0.1.1/vdo-spec-vanilla-k8s.yaml
Tip: now that you have deployed VDO, you might want to try 'vdoctl configure drivers' to configure vsphere drivers

 bin/vdoctl configure cm
✔ Web URL
Web URL https://github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/releases/download/0.1.1/compatibility.yaml

```

```
bin/vdoctl status                                                    
CloudProvider   : Configured
	 vCenter : 
		10.187.159.221  (Credentials Verified)
	 Nodes : 
		 master-vm : ready 
		 worker-vm : ready 
StorageProvider : Deployed
	 vCenter : 
		10.187.159.221  (Credentials Verified)
```

```
kubectl get configmaps -A

vmware-system-csi   internal-feature-states.csi.vsphere.vmware.com   8      5m42s
```

```
kubectl describe configmaps -n vmware-system-csi internal-feature-states.csi.vsphere.vmware.com
Name:         internal-feature-states.csi.vsphere.vmware.com
Namespace:    vmware-system-csi
Labels:       <none>
Annotations:  <none>

Data
====
improved-csi-idempotency:
----
false
improved-volume-topology:
----
false
online-volume-extend:
----
true
trigger-csi-fullsync:
----
false
use-csinode-id:
----
true
async-query-volume:
----
false
csi-auth-check:
----
true
csi-migration:
----
false
```

 ```
kubectl get pods -A       
                                                                     
NAMESPACE           NAME                                      READY   STATUS    RESTARTS   AGE
kube-system         vsphere-cloud-controller-manager-md7fn    1/1     Running   0          9m12s
vmware-system-csi   vsphere-csi-controller-8489c5b7f8-2dvxd   6/6     Running   0          9m12s
vmware-system-csi   vsphere-csi-node-8npc4                    3/3     Running   0          9m12s
vmware-system-csi   vsphere-csi-node-8z66q                    3/3     Running   0          9m12s
vmware-system-vdo   vdo-controller-manager-59b9bc9555-hbsr9   2/2     Running   0          12m
```

**2. Test Results for KIND cluster**

_Tested with CSI version 2.3.0_

```
bin/vdoctl deploy --spec https://github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/releases/download/0.1.1/vdo-spec-vanilla-k8s.yaml
Tip: now that you have deployed VDO, you might want to try 'vdoctl configure drivers' to configure vsphere drivers

bin/vdoctl configure cm
Web URL https://github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/releases/download/0.1.1/compatibility.yaml
Tip: Compatibility matrix has been configured, you might want to try 'vdoctl configure drivers' to configure vsphere drivers.
```

```
bin/vdoctl status
CloudProvider   : Configured
	 vCenter : 
		10.187.159.221  (Credentials Verified)
	 Nodes : 
		 kind-control-plane : ready 
StorageProvider : Deployed
	 vCenter : 
		10.187.159.221  (Credentials Verified)
```

```
kubectl get pods -A

NAMESPACE            NAME                                         READY   STATUS    RESTARTS   AGE
kube-system          vsphere-cloud-controller-manager-2v97k       1/1     Running   0          3m
vmware-system-csi    vsphere-csi-controller-8489c5b7f8-jvmz7      6/6     Running   0          2m52s
vmware-system-csi    vsphere-csi-node-8jch7                       3/3     Running   0          2m52s
vmware-system-vdo    vdo-controller-manager-76f99cb47c-wdxxj      2/2     Running   0          5m43s
```

```
kubectl describe configmaps -n vmware-system-csi internal-feature-states.csi.vsphere.vmware.com
Name:         internal-feature-states.csi.vsphere.vmware.com
Namespace:    vmware-system-csi
Labels:       <none>
Annotations:  <none>

Data
====
improved-csi-idempotency:
----
false
improved-volume-topology:
----
false
online-volume-extend:
----
true
trigger-csi-fullsync:
----
false
use-csinode-id:
----
true
async-query-volume:
----
false
csi-auth-check:
----
true
csi-migration:
----
false
```

2021-12-21 20:19 UTC, asifdxtreme requested changes

2021-12-21 20:19 UTC, asifdxtreme commented on controllers/vdoconfig_controller.go
> +
check for cm.Data != nil 

Suggestion : Rename cm  as it confuses with compatibility matrix in terms of VDO

2021-12-21 20:19 UTC, asifdxtreme commented on controllers/vdoconfig_controller.go
> +		err = r.updateCSIConfigmap(vdoctx)
Suggestion : Add Info log for updating ConfigMap with feature state

2021-12-21 20:19 UTC, asifdxtreme commented on controllers/vdoconfig_controller.go
> +func (r *VDOConfigReconciler) updateCSIConfigmap(ctx vdocontext.VDOContext) error {
Please Add UT for this

2022-01-03 06:33 UTC, asifdxtreme approved these changes
LGTM

2022-01-03 06:36 UTC, jvrahav approved these changes

2022-01-03 06:37 UTC, merged