Update the documents with taint as pre-requisite
vmware-tanzu/vsphere-kubernetes-drivers-operator pull request #140
Opened 2022-01-06 04:45 UTC by ridaz

**What type of PR is this?**
 /kind documentation

**What this PR does / why we need it**:
 This PR will add the following documentation:

In order to bring up CPI and some versions of CSI successfully, the nodes need to be tainted with
node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule

**Which issue(s) this PR fixes**:

Fixes #

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> /kind NOT-TESTED

**Test Report**:

**Special notes for your reviewer**:

2022-01-06 07:32 UTC, aggarwalta approved these changes
LGTM, thanks!

2022-01-07 10:05 UTC, asifdxtreme approved these changes
LGTM

2022-01-10 04:23 UTC, jvrahav requested changes

2022-01-10 04:23 UTC, jvrahav commented on controllers/vdoconfig_controller.go
> +		allNodesReady = false
can we assign this boolean inside the if loop for taints where we set the cpi status as configuring

2022-01-10 04:27 UTC, jvrahav commented on controllers/vdoconfig_controller.go
> +		allNodesReady = false
this will ensure that we are only concerned about nodes that are intended by the user to be managed by cloud provider

2022-01-10 08:50 UTC, jvrahav approved these changes

2022-01-10 08:51 UTC, merged