[WIP] Add auto-upgrade feature via configMap update
vmware-tanzu/vsphere-kubernetes-drivers-operator pull request #18
Opened 2021-09-09 10:39 UTC by asifdxtreme

**What type of PR is this?**
> /kind enhancement

**What this PR does / why we need it**:
This PR adds the support of upgrade scenario where user can update the versions of CPI/CSI without restarting the vdo-controller. 
User need to update the configMap which contains the upgraded version Matrix, and VDO will dynamically listen to any change in the configMap and apply the changes accordingly.

**Which issue(s) this PR fixes**:
Fixes #5 

**Test Report Added?**:
> /kind TESTED

**Special notes for your reviewer**:
 - [ ] addition of UT in Progress

2021-09-09 11:47 UTC, lgayatri approved these changes

2021-09-13 09:44 UTC, jvrahav requested changes

2021-09-13 09:44 UTC, jvrahav commented on main.go
> +	go vdoConfigReconciler.WatchForConfigMapChanges()
why not just setup another watch when setting up the manager 
```

			Watches(
				&source.Kind{Type: &v1.ConfigMap{}},
				handler.EnqueueRequestsFromMapFunc(func(object client.Object) []reconcile.Request {
					cm, _ := object.(*v1.ConfigMap)
					if cm.Namespace == VDO_NAMESPACE && cm.Name == "test-cm" {
						
					}
					return nil
				}))
```
we expect there to be only vdoconfig resource in the cluster. Hence here in the watch we can fetch the vdo config resource and raise a reconcile request for the resource.
we should be leveraging the constructs in controller-runtime libraries to achieve these functionalities
we should also always compare the actual vs desired and perform reconcile to achieve the desired function

2021-09-14 11:02 UTC, jvrahav requested changes

2021-09-14 11:02 UTC, jvrahav commented on controllers/vdoconfig_controller.go
> +				configMap, _ := object.(*v1.ConfigMap)
what happens if the configmap is deleted. should we unset the environment variables

2021-09-15 17:19 UTC, jvrahav approved these changes
can we add a copy of the matrix.yaml in the code base.

2021-09-15 17:19 UTC, jvrahav commented on controllers/vdoconfig_controller_test.go
> +		model := simulator.VPX()
we can avoid spawning a vc sim instance here as we are only looking to create a configmap with vc creds, which can be any random text. bringing up vc sim for this purpose seems to be an excess

2021-09-15 19:21 UTC, merged